import apifyClient from "@/lib/apify/client";
import { ApifyRunInfo } from "@/lib/apify/types";

const DEFAULT_INPUT = {
  downloadSubtitles: false,
  hasCC: false,
  hasLocation: false,
  hasSubtitles: false,
  is360: false,
  is3D: false,
  is4K: false,
  isBought: false,
  isHD: false,
  isHDR: false,
  isLive: false,
  isVR180: false,
  maxResultStreams: 0,
  maxResults: 1,
  maxResultsShorts: 0,
  preferAutoGeneratedSubtitles: false,
  saveSubsToKVS: false,
  subtitlesLanguage: "en",
  subtitlesFormat: "srt",
};

const startYoutubeProfileScraping = async (handle: string): Promise<ApifyRunInfo | null> => {
  const cleanHandle = handle.trim().replace(/^@/, "");

  if (!cleanHandle) {
    throw new Error("Invalid YouTube handle");
  }

  const targetUrl = `https://www.youtube.com/@${cleanHandle}`;

  const input = {
    ...DEFAULT_INPUT,
    startUrls: [{ url: targetUrl }],
  };

  const run = await apifyClient.actor("streamers/youtube-scraper").start(input);

  return {
    runId: run.id,
    datasetId: run.defaultDatasetId,
  };
};

export default startYoutubeProfileScraping;
