/** Shared by proposal, selection, direction and review so their standards cannot contradict. */
export const creativeCriteria = `Judge the actual fan experience with these same criteria at every stage:
- Clear: a visitor understands the action in one short sentence.
- Worth doing: the first action delivers satisfying movement, humor, discovery, skill or expression; the result reflects what the visitor did.
- Obvious connection: the core activity can directly enact the release title, a supplied lyric/theme, an audible musical quality, recognizable artwork or the artist's world. One strong recognizable anchor is sufficient. A literal, playful interpretation is valid; it does not need a deeper explanation, exclusive association with this artist, or proof that the artist intended the activity.
- Honest: distinguish creative adaptation from factual attribution. Invented characters, scenes and games are allowed as creative fiction. Do not invent quotations, artist biography, lyrics or claims about what the song means. Require source evidence for factual claims, not permission from research to imagine an activity.
- Feasible and complete: supported controls lead to the promised payoff on a phone, with no unavailable services or fake results.
Reject a connection when the activity has no recognizable relationship beyond a logo, color palette or pasted-on title. Do not reject a direct title-to-action connection merely for being literal or a pun. Connection and fun are separate checks: an obvious reference can still be dull, and a fun mechanic still needs a recognizable anchor.
Calibration: a song called "Paper Planes" can inspire a satisfying paper-plane flying challenge without evidence that its artist flies paper planes. A generic questionnaire with that title pasted on is not equivalent. Judge craft and the interaction rather than demanding literary analysis. Apply this principle to any release; do not force this example's mechanic.`;
