/** Product preference shared by concept, reference research, implementation and review. */
export const gameplayCriteria = `Default to a short, replayable game for URL-only and open-ended fan-site requests. Prefer play over passive reveals, mood selectors, affirmation generators, poem makers and decorative interactions. Those formats are valid when the customer explicitly requests them or has explicitly selected that concept; do not silently replace an approved activity during a repair. A sad or quiet song can support a thoughtful puzzle or exploration game: genre and mood do not require a passive experience.

For automatic proposals, explore distinct game mechanics before choosing visual treatments: for example skill/timing, spatial or logic puzzles, and tactical choices or discovery with a concrete goal. These are examples, not mandatory genres or templates. Fit the mechanic and world to the release; do not force every song into a runner, quiz or rhythm game. Rhythm-dependent play needs reliable audio timing; otherwise choose a mechanic that remains playable without audio.

A strong game has:
- A goal the fan can state in one sentence and a first playable action within seconds. Teach one mechanic through a forgiving first attempt, not a tutorial wall or mandatory sign-in.
- A repeatable loop: act, receive immediate readable feedback, make the next decision. Timing, positioning, strategy, observation or an actual puzzle solution changes the outcome. Clicking through predetermined reveals is not a game.
- Fair rules and agency: the player can learn what helped or hurt. Show relevant progress and an earned win, score, solved state or survival result. Failure must be recoverable; cozy games need not punish, use timers or have leaderboards.
- Enough variation, mastery or alternative strategies to make another attempt worthwhile. End with a clear result and a fast working replay/reset. Never add meaningless scores, random rewards or a replay button to disguise a one-time animation.
- Release-specific content and art that support play, plus clear mobile controls and responsive feedback. Visual ambition must improve readability and game feel, not obscure the objective.

Prefer the strongest playable loop over the most elaborate metaphor or rationale. Reject arbitrary chores, trivial repeated tapping, personality quizzes with predetermined outcomes, and customization-only toys as default concepts. A title pun alone does not make them fun. Preserve explicit customer format and accessibility constraints.

During direction, specify the objective, inputs, rules, meaningful decisions, first success, end condition and replay variation in the existing activity and journey fields. Include a real round or puzzle, its result and replay in the journey contract. During implementation, build those mechanics before decorative polish; use responsive feedback, forgiving input and clear result transitions. During review, fail fan value for a default concept without a real playable loop. Check actual journey evidence for action-to-outcome, earned results and reset; do not pass because buttons work or screenshots look polished. Do not claim difficulty, fun, motion feel or replay variety has been empirically verified from a single scripted path. Request concrete fixes for observed defects without inventing unsupported tests.`;
