/**
 * Curated list of ~200 notable cities used as memorable, unique
 * fallback titles for sessions that don't have a user-provided title.
 * Ported verbatim from open-agents so generated titles look familiar
 * to the existing frontend.
 */
export const cityNames: readonly string[] = [
  // Africa
  "Abidjan",
  "Accra",
  "Addis Ababa",
  "Algiers",
  "Antananarivo",
  "Cairo",
  "Cape Town",
  "Casablanca",
  "Dakar",
  "Dar es Salaam",
  "Johannesburg",
  "Kampala",
  "Kigali",
  "Kinshasa",
  "Lagos",
  "Luanda",
  "Lusaka",
  "Maputo",
  "Marrakech",
  "Nairobi",
  "Tunis",
  "Windhoek",

  // Asia
  "Almaty",
  "Amman",
  "Baku",
  "Bangkok",
  "Beijing",
  "Beirut",
  "Bengaluru",
  "Bishkek",
  "Colombo",
  "Dhaka",
  "Dubai",
  "Hanoi",
  "Ho Chi Minh City",
  "Hong Kong",
  "Hyderabad",
  "Islamabad",
  "Istanbul",
  "Jakarta",
  "Jeddah",
  "Jerusalem",
  "Kabul",
  "Karachi",
  "Kathmandu",
  "Kolkata",
  "Kuala Lumpur",
  "Kyoto",
  "Manila",
  "Mumbai",
  "Muscat",
  "New Delhi",
  "Osaka",
  "Phnom Penh",
  "Riyadh",
  "Seoul",
  "Shanghai",
  "Shenzhen",
  "Singapore",
  "Taipei",
  "Tashkent",
  "Tbilisi",
  "Tehran",
  "Tel Aviv",
  "Thimphu",
  "Tokyo",
  "Ulaanbaatar",
  "Vientiane",
  "Yangon",
  "Yerevan",

  // Europe
  "Amsterdam",
  "Athens",
  "Barcelona",
  "Belgrade",
  "Berlin",
  "Bern",
  "Bordeaux",
  "Bratislava",
  "Brussels",
  "Bucharest",
  "Budapest",
  "Copenhagen",
  "Dublin",
  "Edinburgh",
  "Florence",
  "Geneva",
  "Hamburg",
  "Helsinki",
  "Kraków",
  "Kyiv",
  "Lisbon",
  "Ljubljana",
  "London",
  "Lyon",
  "Madrid",
  "Marseille",
  "Milan",
  "Minsk",
  "Monaco",
  "Moscow",
  "Munich",
  "Naples",
  "Oslo",
  "Paris",
  "Porto",
  "Prague",
  "Reykjavik",
  "Riga",
  "Rome",
  "Sarajevo",
  "Seville",
  "Sofia",
  "Stockholm",
  "Tallinn",
  "Valencia",
  "Venice",
  "Vienna",
  "Vilnius",
  "Warsaw",
  "Zagreb",
  "Zurich",

  // North America
  "Anchorage",
  "Atlanta",
  "Austin",
  "Boston",
  "Calgary",
  "Chicago",
  "Denver",
  "Detroit",
  "Guadalajara",
  "Havana",
  "Honolulu",
  "Houston",
  "Kingston",
  "Los Angeles",
  "Mexico City",
  "Miami",
  "Minneapolis",
  "Montreal",
  "Nashville",
  "New Orleans",
  "New York",
  "Ottawa",
  "Philadelphia",
  "Phoenix",
  "Portland",
  "San Diego",
  "San Francisco",
  "San Juan",
  "Seattle",
  "Toronto",
  "Vancouver",
  "Washington",

  // South America
  "Bogotá",
  "Brasília",
  "Buenos Aires",
  "Caracas",
  "Cartagena",
  "Cusco",
  "Guayaquil",
  "La Paz",
  "Lima",
  "Medellín",
  "Montevideo",
  "Quito",
  "Recife",
  "Rio de Janeiro",
  "Santiago",
  "São Paulo",
  "Valparaíso",

  // Oceania
  "Adelaide",
  "Auckland",
  "Brisbane",
  "Christchurch",
  "Fiji",
  "Melbourne",
  "Perth",
  "Sydney",
  "Wellington",
];
