import { build } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";
const result = await build({
  entryPoints: ["ui/recoup/main.ts"],
  bundle: true,
  write: false,
  format: "iife",
  target: "es2022",
  minify: true,
  loader: { ".woff2": "dataurl", ".svg": "dataurl" },
});
let css = await readFile("ui/recoup/style.css", "utf8");
for (const font of ["dm-sans", "ibm-plex-mono"]) {
  const bytes = await readFile(`ui/recoup/assets/${font}.woff2`);
  css = css.replace(`assets/${font}.woff2`, `data:font/woff2;base64,${bytes.toString("base64")}`);
}
const wordmark = `data:image/svg+xml;base64,${(await readFile("ui/recoup/assets/wordmark-light.svg")).toString("base64")}`;
const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Recoup</title><style>${css}</style></head><body><div id="root"></div><script>${result.outputFiles[0].text.replace("__WORDMARK__", wordmark).replaceAll("</script", "<\\/script")}</script></body></html>`;
await writeFile(
  "lib/mcp/extension/generated-ui.ts",
  `// Generated by scripts/mcp-extension/build.mjs.\nexport default ${JSON.stringify(html)};\n`,
);
await writeFile("ui/recoup/preview.html", html);
console.log(`Built Recoup extension (${Math.round(Buffer.byteLength(html) / 1024)} KB)`);
