/**
 * The auto top-up columns on `credits_usage`, added by recoupable/database#69.
 *
 * `types/database.types.ts` is generated by `pnpm update-types` and must not
 * be hand-edited; until it is regenerated after that migration is applied,
 * the two supabase-layer readers/writers cast through this row type. Once the
 * generated `Tables<"credits_usage">` carries these columns, replace this
 * type with `Pick<Tables<"credits_usage">, ...>` and drop the casts.
 */
export interface AutoTopUpRow {
  account_id: string;
  auto_topup_enabled: boolean;
  /** Credit micro-dollars per top-up; null until set. */
  auto_topup_amount: number | null;
  /** Balance in credit micro-dollars below which a top-up runs; null until set. */
  auto_topup_threshold: number | null;
  auto_topup_last_run_at: string | null;
  auto_topup_last_error: string | null;
}

export const AUTO_TOP_UP_COLUMNS =
  "account_id, auto_topup_enabled, auto_topup_amount, auto_topup_threshold, auto_topup_last_run_at, auto_topup_last_error";

export function pickAutoTopUpRow(row: Record<string, unknown>): AutoTopUpRow {
  return {
    account_id: row.account_id as string,
    auto_topup_enabled: Boolean(row.auto_topup_enabled),
    auto_topup_amount: (row.auto_topup_amount as number | null) ?? null,
    auto_topup_threshold: (row.auto_topup_threshold as number | null) ?? null,
    auto_topup_last_run_at: (row.auto_topup_last_run_at as string | null) ?? null,
    auto_topup_last_error: (row.auto_topup_last_error as string | null) ?? null,
  };
}
