export const worldGuidance = `BRAND WORLD, NOT COVER DECORATION
Create one coherent, specific design system. The system must survive removing the displayed cover. Translate artwork into spatial composition, material behavior, shape vocabulary, typography, interaction and a hierarchy of attention; do not simply display the cover over a matching background.
Choose a composition that fits the actual customer purpose: an immersive scene, an editorial sequence, a focused tool or another justified structure. Neither a full-screen game nor a split hero/card layout is a universal template. If no game is requested, do not force game mechanics into the site.
Define a dominant visual idea, a restrained supporting vocabulary, what must be preserved, and what would break the identity. Color roles need readable foregrounds and surfaces, not only accents. Express source lettering through appropriate type proportions, weight, rhythm and hierarchy; avoid crude imitations of complex custom lettering.
High quality can be playful, raw, minimal, photographic, typographic or maximalist. Do not equate premium with monochrome minimalism, or illustration with thick outlines, tilted cards and offset shadows. Use any such device only when supported by the source and composed deliberately. Avoid unrelated mascots, stock emoji, generic blobs, invented sub-brands, slogans and decorative badges.
Decide the asset strategy honestly. Supplied assets use their exact indices. Procedural Canvas, SVG and native WebGL can deliver rich illustrations, articulated characters, painterly textures and dimensional environments when their actual drawing, lighting and motion systems are implemented. Choose the medium deliberately: stable seeded texture for print, rigs and grounded contacts for characters, layered lighting for space. Do not settle for primitive clip art simply because code is the medium. Photography or generated media still requires real supplied assets. If essential art is unavailable, mark it defer and choose a complete, restrained fallback using actual available assets; never promise nonexistent image generation, fabricate URLs, or replace the missing art with low-quality clip art. Asset production may be added later through this same plan.
Define the first frame composition, one defining interactive moment, how its material moves, and a result that visibly rewards the fan. Specify timing, easing, anticipation, response and a recognition hold where they matter. Select a complementary visual and motion reference from the supplied skill guidance and state the mechanism being adapted.
Map the world to entry, experience, controls, connection, player, completion, loading and error states. Trusted Recoup connection/player controls live outside generated HTML and currently accept only background, foreground, accent and serif/sans theme fields. Adapt those fields honestly; do not claim custom provider-auth screens or unsupported widget layouts.
On revision, preserve the prior concept, visual signatures and asset strategy unless the latest instruction or changed sources require a change. A small text/control edit must not redesign the whole world. Record the requested override explicitly.`;
