import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { createSegments } from "@/lib/segments/createSegments";
import { getToolResultSuccess } from "@/lib/mcp/getToolResultSuccess";
import { getToolResultError } from "@/lib/mcp/getToolResultError";

const createSegmentsSchema = z.object({
  artist_account_id: z
    .string()
    .min(1, "Artist account ID is required")
    .describe(
      "The artist_account_id to create segments for. If not provided, check system prompt for the active artist_account_id.",
    ),
  prompt: z
    .string()
    .min(1, "Prompt is required")
    .describe(
      "The prompt to use for generating segment names. This should be generated by the system if not provided.",
    ),
});

export type CreateSegmentsArgs = z.infer<typeof createSegmentsSchema>;

/**
 * Registers the "create_segments" tool on the MCP server.
 * Creates segments by analyzing fan data and generating segment names.
 *
 * @param server - The MCP server instance to register the tool on.
 */
export function registerCreateSegmentsTool(server: McpServer): void {
  server.registerTool(
    "create_segments",
    {
      description:
        "Create segments by analyzing fan data and generating segment names. This tool fetches all fans for an artist, generates segment names based on the provided prompt, and saves the segments to the database. If required information is missing (social accounts or fan data), the tool will provide step-by-step instructions to gather the missing prerequisites using other available tools.",
      inputSchema: createSegmentsSchema,
    },
    async (args: CreateSegmentsArgs) => {
      try {
        const result = await createSegments(args);

        if (result.success) {
          return getToolResultSuccess(result);
        }

        return getToolResultError(result.message || "Failed to create segments");
      } catch (error) {
        console.error("Error creating segments:", error);
        return getToolResultError(
          error instanceof Error ? error.message : "Failed to create segments",
        );
      }
    },
  );
}
